# frozen_string_literal: true

module Constants
  module Cities
    LIST = %w[Kyiv
              Kharkiv
              Odesa
              Dnipro
              Donetsk
              Zaporizhzhia
              Lviv
              Kryvyy Rih
              Mykolaiv
              Mariupol
              Sevastopol
              Luhansk
              Vinnytsia
              Makiivka
              Simferopol
              Poltava
              Chernihiv
              Kherson
              Cherkasy
              Khmelnytskyi
              Zhytomyr
              Chernivtsi
              Sumy
              Horlivka
              Rivne
              Ivano-Frankivsk
              Kamianske
              Kremenchuk
              Kropyvnytskyi
              Ternopil
              Lutsk
              Bila Tserkva
              Kramatorsk
              Melitopol’
              Sievierodonetsk
              Kerch
              Khrustalnyi
              Uzhhorod
              Berdyans’k
              Sloviansk
              Nikopol’
              Yevpatoriya
              Pavlohrad
              Alchevsk
              Konotop
              Lysychansk
              Brovary
              Kam”yanets’-Podil’s’kyy
              Drohobych
              Dovzhansk
              Mukacheve
              Uman’
              Chervonohrad
              Yalta
              Yenakiieve
              Shostka
              Berdychiv
              Bakhmut
              Stakhanov
              Nizhyn
              Kostiantynivka
              Izmayil
              Novomoskovs’k
              Nova Kakhovka
              Kovel’
              Smila
              Feodosiya
              Kalush
              Korosten
              Pokrovsk
              Boryspil’
              Kolomyya
              Rubizhne
              Chornomors’k
              Khartsyzk
              Druzhkivka
              Stryy
              Bilhorod-Dnistrovs’kyy
              Irpin’
              Novohrad-Volynskyi
              Lozova
              Antratsyt
              Enerhodar
              Novovolynsk
              Horishni Plavni
              Myrnohrad
              Shakhtarsk
              Okhtyrka
              Brianka
              Snizhne
              Marhanets’
              Rovenky
              Fastiv
              Lubny
              Svitlovods’k
              Zhovti Vody
              Krasnodon
              Shepetivka
              Vyshneve
              Romny
              Myrhorod
              Podilsk
              Pokrov
              Volodymyr-Volyns’kyy
              Pervomaisk
              Dzhankoy
              Vasyl’kiv
              Dubno
              Boryslav
              Netishyn
              Holubivske
              Boyarka
              Yasynuvata
              Voznesens’k
              Bucha
              Sambir
              Avdiivka
              Zhmerynka
              Toretsk
              Hlukhiv
              Obukhiv
              Chuhuiv
              Yuzhne
              Kostopil’
              Tokmak
              Mohyliv-Podil’s’kyy
              Synel’nykove
              Novoyavorovskoye
              Pervomaiskyi
              Alushta
              Chortkiv
              Balakliia
              Truskavets’
              Novyy Rozdil
              Khust
              Pershotravens’k
              Ternivka
              Khrestivka
              Khmil’nyk
              Zolotonosha
              Vyshhorod
              Bakhchysaray
              Pereyaslav-Khmel’nyts’kyy
              Malyn
              Perevalsk
              Yany Kapu
              Haysyn
              Korostyshiv
              Vynohradiv
              Slavutych
              Saky
              Kaniv
              Zolochiv
              Selydove
              Brody
              Berehove
              Kozyatyn
              Vil’nohirs’k
              Molodohvardiisk
              Znam”yanka
              Ladyzhyn
              Nadvirna
              Lyman
              Armyans’k
              Sukhodilsk
              Sokal’
              Liubotyn
              Kremenets’
              Dolyna
              Heniches’k
              Yahotyn
              Pidhorodne
              Balta
              Dolyns’ka
              Kalynivka
              Polohy
              P”yatykhatky
              Starobilsk
              Vovchansk
              Skadovs’k
              Dniprorudne
              Svatove
              Amvrosiivka
              Korsun’-Shevchenkivs’kyy
              Lutuhyne
              Bolhrad
              Svalyava
              Zvenyhorodka
              Zmiiv
              Izyaslav
              Vatutine
              Sudak
              Horodok
              Berezan’
              Bilohirs’k
              Verkhivtseve
              Bar
              Horodok
              Skvyra
              Ovruch
              Putyvl’
              Vinnichki
              Novo-Voznesenovka
              Ostroh
              Rakhiv
              Bohodukhiv
              Bilopillya
              Tul’chyn
              Vil’nyans’k
              Burshtyn
              Ochakiv
              Hulyaypole
              Radomyshl
              Orikhiv
              Hola Prystan’
              Zolote
              Lebedyn
              Kivertsi
              Zhashkiv
              Zhovkva
              Horodyshche
              Apostolove
              Tal’ne
              Kaharlyk
              Vasylivka
              Izyum
              Yavoriv
              Tetiyiv
              Rozhyshche
              Bershad’
              Kam”yanka-Dniprovs’ka
              Shchastia
              Buchach
              Kamin’-Kashyrs’kyy
              Hnivan’
              Beryslav
              Vakhrusheve
              Uzyn
              Ukrainsk
              Baranivka
              Nemyriv
              Prymors’k
              Mena
              Mala Vyska
              Kalmiuske
              Lokhvytsya
              Myronivka
              Snovsk
              Hirnyk
              Illintsi
              Zhydachiv
              Bobrynets’
              Hrebinka
              Khrystynivka
              Shcholkine
              Bolekhiv
              Lyuboml’
              Olevsk
              Verkhn’odniprovs’k
              Oster
              Borzna
              Inkerman
              Tarashcha
              Radyvyliv
              Snyatyn
              Pereshchepyne
              Zin’kiv
              Berezivka
              Kobelyaky
              Khodoriv
              Pohrebyshche
              Dubrovytsya
              Staryy Krym
              Tysmenytsya
              Irshava
              Khotyn
              Valky
              Kalanchak
              Horokhiv
              Horodenka
              Tyachiv
              Pomichna
              Chyhyryn
              Monastyryshche
              Chop
              Tlumach
              Barvynkove
              Rava-Rus’ka
              Solotvyno
              Bus’k
              Andrushivka
              Kosiv
              Lypovets’
              Zavodske
              Yaremche
              Rohatyn
              Pivdenne
              Novoselytsya
              Artemivsk
              Rzhyshchiv
              Shyryayeve
              Molochans’k
              Sharhorod
              Vorozhba
              Pryvillya
              Kupiansk
              Oleksandrivsk
              Perechyn
              Lityn
              Staryy Sambir
              Sudova Vyshnya
              Blahovishchenske
              Halych
              Morshyn
              Chudniv
              Dobromyl’
              Miusynsk
              Svyatohirs’k
              Almazna
              Vyzhnytsya
              Skalat
              Bibrka
              Komarno
              Novyy Kalyniv
              Hlynyany
              Baturyn
              Hertsa
              Slavuta
              Pervomays’k
              Dobropillia
              Mykolayiv
              Pustomyty
              Ovidiopol’
              Kitsman’
              Hlyboka
              Derhachi
              Bohorodchany
              Sokyryany
              Zdolbuniv
              Zastavna
              Storozhynets’
              Dobroslav
              Zalishchyky
              Bilyayivka
              Mostys’ka
              Zbarazh
              Borshchiv
              Trostyanets’
              Reni
              Kam”yanka-Buz’ka
              Borodyanka
              Berezhany
              Kel’mentsi
              Marinka
              Monastyrys’ka
              Hayvoron
              Terebovlya
              Rozhnyativ
              Volnovakha
              Kozova
              Dunaivtsi
              Isliam-Terek
              Sarny
              Yampil’
              Baryshivka
              Kurman
              Polonne
              Starokostiantyniv
              Hoshcha
              Pidvolochys’k
              Nyzhn’ohirs’kyy
              Krasnohrad
              Bilozerka
              Oleshky
              Ivanychi
              Novovorontsovka
              Volochys’k
              Tyvriv
              Slovianoserbsk
              Volovets’
              Petropavlivka
              Zboriv
              Chemerivtsi
              Husyatyn
              Bohuslav
              Mlyniv
              Lanivtsi
              Kiliya
              Korets’
              Krasyliv
              Peremyshlyany
              Shpola
              Radekhiv
              Turka
              Rozdil’na
              Mizhhir”ya
              Khoroshiv
              Tomashpil’
              Pidhaytsi
              Rokytne
              Kam”yanka
              Karlivka
              Starobesheve
              Ratne
              Shums’k
              Ichki
              Kryzhopil’
              Man’kivka
              Vinkivtsi
              Teofipol
              Berezne
              Novoazovsk
              Nova Ushytsia
              Pyryatyn
              Teplyk
              Derazhnia
              Verkhniy Rohachyk
              Bilohir”ya
              Katerynopil’
              Pishchanka
              Chernivtsi
              Liubar
              Stavyshche
              Chornobay
              Manhush
              Petrykivka
              Cherniakhiv
              Demydivka
              Velykyy Bereznyy
              Kodyma
              Trostyanets’
              Volodymyrets’
              Hadyach
              Sarata
              Khorol
              Lysyanka
              Skole
              Yarmolyntsi
              Hornostayivka
              Kakhovka
              Popilnia
              Artsyz
              Tatarbunary
              Lokachi
              Savran’
              Holovanivs’k
              Stara Syniava
              Kryve Ozero
              Krolevets’
              Romaniv
              Drabiv
              Chechel’nyk
              Letychiv
              Murovani Kurylivtsi
              Putyla
              Pokrovs’ke
              Krasnokutsk
              Snihurivka
              Tsarychanka
              Velyka Novosilka
              Lyubashivka
              Bakhmach
              Rozdol’ne
              Varva
              Popasna
              Yakymivka
              Stara Vyzhivka
              Volodarka
              Makariv
              Dykan’ka
              Ruzhyn
              Anan’yiv
              Shyshaky
              Pulyny
              Nova Vodolaha
              Mykhaylivka
              Kehychivka
              Novomyrhorod
              Yampil’
              Chutove
              Reshetylivka
              Zolochiv
              Dobrovelychkivka
              Hlobyne
              Novi Sanzhary
              Novoukrayinka
              Tomakivka
              Zarichne
              Stanytsia Luhanska
              Lyubeshiv
              Vasyl’kivka
              Orativ
              Pervomays’ke
              Novyy Buh
              Kreminna
              Nosivka
              Orzhytsya
              Kotel’va
              Manevychi
              Nikolske
              Pechenihy
              Velyka Pysarivka
              Bobrovytsya
              Verkhovyna
              Brusyliv
              Nova Odesa
              Velyka Bahachka
              Oleksandrivka
              Yedy-Kuiu
              Solone
              Rokytne
              Chornomors’ke
              Buryn’
              Shats’k
              Lypova Dolyna
              Nedryhayliv
              Ivanivka
              Chaplynka
              Bashtanka
              Boikivske
              Turiys’k
              Krasnopillya
              Shyroke
              Novopskov
              Mashivka
              Zakharivka
              Mahdalynivka
              Vysokopillya
              Vradiyivka
              Shevchenkove
              Onufriyivka
              Krynychky
              Velyka Mykhaylivka
              Tarutyne
              Z·hurivka
              Arbuzynka
              Sosnytsya
              Kozel’shchyna
              Petrove
              Semenivka
              Novotroyits’ke
              Mezhova
              Talalayivka
              Kolomak
              Ichnya
              Pryluky
              Borova
              Oleksandrivka
              Novoarkhanhel’s’k
              Okny
              Oleksandriya
              Vil’shanka
              Velykyi Burluk
              Sribne
              Zachepylivka
              Berezanka
              Koryukivka
              Kozelets’
              Vesele
              Sakhnovshchyna
              Veselynove
              Bilmak
              Horodnya
              Kulykivka
              Korop
              Domanivka
              Velyka Oleksandrivka
              Luhyny
              Pryazovs’ke
              Brats’ke
              Novomykolayivka
              Velyka Lepetykha
              Sofiyivka
              Bereznehuvate
              Dvorichna
              Velyka Bilozerka
              Chornukhy
              Novoaidar
              Yur”yivka
              Yemilchyne
              Novhorodka
              Kompaniyivka
              Seredyna-Buda
              Yelanets’
              Kazanka
              Bilovodsk
              Novhorod-Sivers’kyy
              Mykolayivka
              Ustynivka
              Rozivka
              Ripky
              Chernihivka
              Milove
              Blyzniuky
              Markivka
              Bilokurakyne
              Troitske
              Nyzhni Sirohozy
              Semenivka
              Ivanivka
              Ivankiv
              Narodychi
              Krasyatychi].freeze
  end
end
